labels_filename: head_nod_head_shake_labels.txt
model_filename: head_nod_head_shake_model.tflite
num_results: 1
data_format:
  num_values_per_sensor_dimenion: 80
  sample_period: 10
  sensor_dimension_ordering:
    - gyro_x
    - gyro_y
    - gyro_z
  normalization_value: [1.0, 1.0, 1.0]
