labels_filename: nine_gestures_labels.txt
model_filename: nine_gestures_model.tflite
num_results: 1
data_format:
  num_values_per_sensor_dimenion: 75
  sample_period: 10
  sensor_dimension_ordering:
    - gyro_x
    - gyro_y
    - gyro_z
  normalization_value: [1.0, 1.0, 1.0]
