labels_filename: activity_recognition_labels.txt
model_filename: activity_recognition_model.tflite
num_results: 1
data_format:
  num_values_per_sensor_dimenion: 80
  sample_period: 40
  sensor_dimension_ordering:
    - accel_x
    - accel_y
    - accel_z
  normalization_value: [1.0, 1.0, 1.0]
