labels_filename: look_left_look_up.txt
model_filename: TFKerasModel_to_TFlite_look_left_look_up.tflite
num_results: 1
data_format:
  num_values_per_sensor_dimenion: 120
  sample_period: 10
  sensor_dimension_ordering:
    - gyro_x
    - gyro_z
  normalization_value: [1.0, 1.0]
